# Generated by Django 5.2.5 on 2025-09-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('invoice_no', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('order_number', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='salesorder',
            unique_together={('order_number', 'company')},
        ),
    ]
