# Generated by Django 5.2.5 on 2025-09-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_invoice_invoice_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_on',
            field=models.DateField(auto_now=True),
        ),
    ]
