# Generated by Django 5.2.5 on 2025-08-11 14:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_route_routevisit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteLocationPing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('speed_mps', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heading_degrees', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='routevisit',
            name='transaction_route_i_bd2806_idx',
        ),
        migrations.AlterUniqueTogether(
            name='routevisit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='routelocationping',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='transactions.route'),
        ),
        migrations.AddField(
            model_name='routelocationping',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_pings', to='transactions.routevisit'),
        ),
        migrations.AddIndex(
            model_name='routelocationping',
            index=models.Index(fields=['route', 'created_at'], name='transaction_route_i_1b0c4d_idx'),
        ),
    ]
