# Generated by Django 5.2.5 on 2025-09-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_salesorder_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='gone_for_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
