# Generated by Django 5.2.5 on 2025-09-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_salesorder_gone_for_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(help_text='Due date from frontend - used as credit expiry date'),
        ),
    ]
