# Generated by Django 5.2.5 on 2025-08-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_routelocationping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='prices_include_vat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='prices_include_vat',
            field=models.BooleanField(default=False),
        ),
    ]
