# Generated by Django 4.2.4 on 2025-08-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_purchaseorder_prices_include_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
