# Generated by Django 4.2.4 on 2025-08-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_purchaseorder_order_number_salesorder_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['route_number'], name='transaction_route_n_b21e86_idx'),
        ),
    ]
