# Generated by Django 4.2.4 on 2025-08-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_route_route_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routevisit',
            name='sales_orders',
            field=models.ManyToManyField(blank=True, related_name='route_visits', to='transactions.salesorder'),
        ),
    ]
