# Generated by Django 4.2.4 on 2025-08-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_routevisit_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routelocationping',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='routelocationping',
            name='lon',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
