# Generated by Django 4.2.4 on 2025-08-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_update_gps_coordinates_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routelocationping',
            name='accuracy_meters',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='routelocationping',
            name='speed_mps',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
