# Generated by Django 4.2.4 on 2025-08-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_update_gps_accuracy_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='routevisit',
            name='issues_reported',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='routevisit',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='routevisit',
            name='payment_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routevisit',
            name='visit_duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
