# Generated by Django 5.2.5 on 2025-08-16 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_routevisit_issues_reported_routevisit_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='salesperson',
        ),
    ]
