# Generated by Django 5.2.5 on 2025-08-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_remove_salesorder_salesperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routelocationping',
            name='accuracy_meters',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
