# Generated by Django 5.2.5 on 2025-08-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_routelocationping_accuracy_meters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routelocationping',
            name='accuracy_meters',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
