# Generated by Django 5.2.5 on 2025-09-01 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_company'),
        ('transactions', '0016_alter_routelocationping_accuracy_meters'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routelocationping',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='route_location_pings', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routevisit',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='route_visits', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='accounts.company'),
            preserve_default=False,
        ),
    ]
