# Generated by Django 5.2.5 on 2025-10-01 15:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text="Name of the model being audited (e.g., 'Customer', 'Invoice')", max_length=100)),
                ('record_number', models.CharField(blank=True, help_text="Record identifier (e.g., 'INV-1001', 'SO-2001')", max_length=100, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('block', 'Block'), ('unblock', 'Unblock'), ('read', 'Read')], help_text='Action performed on the record', max_length=20)),
                ('before_data', models.JSONField(blank=True, help_text='Data before the change (for updates)', null=True)),
                ('after_data', models.JSONField(blank=True, help_text='Data after the change', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the action was performed')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name'], name='audit_audit_model_n_515731_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['performed_by'], name='audit_audit_perform_19e3dd_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx')],
            },
        ),
    ]
