# Generated by Django 5.2.5 on 2025-09-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('salesperson', 'Salesperson'), ('accountant', 'Accountant')], default='salesperson', max_length=20),
        ),
    ]
