# Generated by Django 5.2.5 on 2025-09-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('main', '0002_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='vatsettings',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('email', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('code', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('email', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='vatsettings',
            unique_together={('category', 'company')},
        ),
    ]
