# Generated by Django 5.2.5 on 2025-09-28 03:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customer_email_alter_product_code_and_more'),
        ('transactions', '0005_salesorder_gone_for_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='credit_limit',
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_expire_days',
            field=models.IntegerField(default=30),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('payed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='transactions.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
